### ISSUE TITLE
[feature request] tab through windows, not apps

### ISSUE THREAD

**Issue by tobyink** [kwalo/gnome-shell-alt-tab-workspace#17]
If I have a couple of browser windows open, a few terminals, and a handful of other apps, I want to be able to use Alt-Tab to get to any of the windows.

Yes, I know I can find the right app then use the arrows to select the window I want, but that's a two handed thing and doesn't feel anywhere near as natural as just being able to Alt-Tab to exactly the window I want.

**Comment by tobyink** [comment]
(And yes, I figure this should probably be a configurable option rather than changing the behaviour for everybody.)

**Comment by kwalo** [comment]
There are other extensions that have this feature. You should use them
instead.

pt., 6 gru 2019, 12:28 użytkownik Toby Inkster <notifications@github.com>
napisał:

**Comment by tobyink** [comment]
Are there any that only do so for the current workspace though?

**Comment by kwalo** [comment]
Check this one for example:
https://extensions.gnome.org/extension/38/windows-alt-tab/



pon., 9 gru 2019, 01:49 użytkownik Toby Inkster <notifications@github.com>
napisał:

**Comment by tobyink** [comment]
That hasn't been updated in years and when I've tried it in the past, has just crashed my gnome-shell.

**Comment by tobyink** [comment]
Oh cool, this works though!
https://blogs.gnome.org/fmuellner/2018/10/11/the-future-of-alternatetab-and-why-you-need-not-worry/
